/**
 * Auto-generated by scripts/download-figma-assets.mjs
 *
 * Maps Figma Desktop localhost asset URLs to local paths under public/assets/figma/.
 * Re-run the script whenever new designs are fetched from Figma Desktop to keep in sync.
 */

const FIGMA_ASSET_MAP: Record<string, string> = {
  '/assets/figma/032bfe46a059793c4196f19fa0f01e723545dd87.png': '/assets/figma/032bfe46a059793c4196f19fa0f01e723545dd87.png',
  '/assets/figma/263f23cec5aa0022aa6b0a0858fd7a55f0cc68b9.png': '/assets/figma/263f23cec5aa0022aa6b0a0858fd7a55f0cc68b9.png',
  '/assets/figma/277f1a1038cf4600b17f6723a28c11133b9c42a5.png': '/assets/figma/277f1a1038cf4600b17f6723a28c11133b9c42a5.png',
  '/assets/figma/2d322ae6c60c8b48ccba899110265eb26751c9e2.svg': '/assets/figma/2d322ae6c60c8b48ccba899110265eb26751c9e2.svg',
  '/assets/figma/2e155351b3c6de50454338cb8b24304fadf71ae7.png': '/assets/figma/2e155351b3c6de50454338cb8b24304fadf71ae7.png',
  '/assets/figma/2f1009afcdf759e231a041ad0daafab2cff622d0.png': '/assets/figma/2f1009afcdf759e231a041ad0daafab2cff622d0.png',
  '/assets/figma/31326f901f95282b1a6396f82280465268b9e670.png': '/assets/figma/31326f901f95282b1a6396f82280465268b9e670.png',
  '/assets/figma/341ab9dd02d861ee02055e75893b9a057df23021.png': '/assets/figma/341ab9dd02d861ee02055e75893b9a057df23021.png',
  '/assets/figma/3a1e52ece350c3cd3815a476bdd9c3ac93f6cc2f.svg': '/assets/figma/3a1e52ece350c3cd3815a476bdd9c3ac93f6cc2f.svg',
  '/assets/figma/3f96c7e59b759adb3311f89c719da75feaca6a0c.png': '/assets/figma/3f96c7e59b759adb3311f89c719da75feaca6a0c.png',
  '/assets/figma/3fdfcee2ff264aa67fc624231b531a818ad5fa42.svg': '/assets/figma/3fdfcee2ff264aa67fc624231b531a818ad5fa42.svg',
  '/assets/figma/49c1ec69ffc199a3c1886a818113552c623a18fe.png': '/assets/figma/49c1ec69ffc199a3c1886a818113552c623a18fe.png',
  '/assets/figma/5100247fb8aac48ecff86bb2e97b8dbbb989f11d.png': '/assets/figma/5100247fb8aac48ecff86bb2e97b8dbbb989f11d.png',
  '/assets/figma/588e358e5eb2165638e4d156e06e5987b2b02be8.png': '/assets/figma/588e358e5eb2165638e4d156e06e5987b2b02be8.png',
  '/assets/figma/5909a9a359257c6c00e050bd492db4aac9c4d96d.svg': '/assets/figma/5909a9a359257c6c00e050bd492db4aac9c4d96d.svg',
  '/assets/figma/5c60231921be44e81e983732d227140b2bc4ab2c.png': '/assets/figma/5c60231921be44e81e983732d227140b2bc4ab2c.png',
  '/assets/figma/5e18319f2a491e8950e8e7903851e0c43db912ab.png': '/assets/figma/5e18319f2a491e8950e8e7903851e0c43db912ab.png',
  '/assets/figma/617f16d4d6683029a0fc4db434dc7801ce1779e3.svg': '/assets/figma/617f16d4d6683029a0fc4db434dc7801ce1779e3.svg',
  '/assets/figma/657e248134a12fab651ac8e67bed14dc2f5e190a.png': '/assets/figma/657e248134a12fab651ac8e67bed14dc2f5e190a.png',
  '/assets/figma/6c3cf40c58f783b0a3e6577ebbadd26c0e005675.png': '/assets/figma/6c3cf40c58f783b0a3e6577ebbadd26c0e005675.png',
  '/assets/figma/6cd0e6362a73050667423418aae84ecb14f0f736.png': '/assets/figma/6cd0e6362a73050667423418aae84ecb14f0f736.png',
  '/assets/figma/705537c0d3b7be60ebf845f2184b6902e544f36e.png': '/assets/figma/705537c0d3b7be60ebf845f2184b6902e544f36e.png',
  '/assets/figma/74416f5acde65a0356ae4afadffc010a242e4de2.png': '/assets/figma/74416f5acde65a0356ae4afadffc010a242e4de2.png',
  '/assets/figma/7a6c03f220dd2a00f6afea792253ca3616959da0.svg': '/assets/figma/7a6c03f220dd2a00f6afea792253ca3616959da0.svg',
  '/assets/figma/7e9e56a0b64002229e435b4ad7cbca2ea41af288.png': '/assets/figma/7e9e56a0b64002229e435b4ad7cbca2ea41af288.png',
  '/assets/figma/80a7afb26cde0512ec08a60d2a1b2765396fabb4.png': '/assets/figma/80a7afb26cde0512ec08a60d2a1b2765396fabb4.png',
  '/assets/figma/8572190f05c08d3d2b312a3e28a36a7b0adc1b9d.svg': '/assets/figma/8572190f05c08d3d2b312a3e28a36a7b0adc1b9d.svg',
  '/assets/figma/882ce8b538d97d996dafe358a114b6033487eb12.svg': '/assets/figma/882ce8b538d97d996dafe358a114b6033487eb12.svg',
  '/assets/figma/9124f01a0cdf562646ac41c52b5f2cab2625bd09.svg': '/assets/figma/9124f01a0cdf562646ac41c52b5f2cab2625bd09.svg',
  '/assets/figma/9306d890f91dac885c452dadad6002925b5c21d6.png': '/assets/figma/9306d890f91dac885c452dadad6002925b5c21d6.png',
  '/assets/figma/939127241329aed177882aa617dc4b47d1e350c2.png': '/assets/figma/939127241329aed177882aa617dc4b47d1e350c2.png',
  '/assets/figma/973c3b8c0dd37d2ff37f9479e563cabfa2a227de.png': '/assets/figma/973c3b8c0dd37d2ff37f9479e563cabfa2a227de.png',
  '/assets/figma/9d6d5c6ff44924f668f3e336b96bd4380d7c1ec2.png': '/assets/figma/9d6d5c6ff44924f668f3e336b96bd4380d7c1ec2.png',
  '/assets/figma/a0354aeef93930d0e1ee44cc1bbc74f70bebb187.png': '/assets/figma/a0354aeef93930d0e1ee44cc1bbc74f70bebb187.png',
  '/assets/figma/a4cf20229701efce127d8f1db9b04fa938ab5fa9.png': '/assets/figma/a4cf20229701efce127d8f1db9b04fa938ab5fa9.png',
  '/assets/figma/a506e2f729dc458b242fd0aa15182a5797f22294.png': '/assets/figma/a506e2f729dc458b242fd0aa15182a5797f22294.png',
  '/assets/figma/a94a781d3ccee95ab1957f0c1b3fd07a2491a8fb.svg': '/assets/figma/a94a781d3ccee95ab1957f0c1b3fd07a2491a8fb.svg',
  '/assets/figma/b351147b3dc113ab4c0918d6e6fb35cc4538f7a4.svg': '/assets/figma/b351147b3dc113ab4c0918d6e6fb35cc4538f7a4.svg',
  '/assets/figma/b5227f239659a5a7d59a309a71035853050ce485.png': '/assets/figma/b5227f239659a5a7d59a309a71035853050ce485.png',
  '/assets/figma/b69e1f2044286b5156fd1d8b21a96c5656bdbd30.png': '/assets/figma/b69e1f2044286b5156fd1d8b21a96c5656bdbd30.png',
  '/assets/figma/ba5499929917b59556aca9b4ac04748a9d601413.png': '/assets/figma/ba5499929917b59556aca9b4ac04748a9d601413.png',
  '/assets/figma/bb58655a57d80a328c43b89c58da982691332c16.png': '/assets/figma/bb58655a57d80a328c43b89c58da982691332c16.png',
  '/assets/figma/bdcd8239da68974f9d77f458f86320eab6a49d30.svg': '/assets/figma/bdcd8239da68974f9d77f458f86320eab6a49d30.svg',
  '/assets/figma/be12d4260d4d66bf2dec1b208ca3099fe511e0da.png': '/assets/figma/be12d4260d4d66bf2dec1b208ca3099fe511e0da.png',
  '/assets/figma/be35d34a24d15524a9c0126750ae432b82dab795.png': '/assets/figma/be35d34a24d15524a9c0126750ae432b82dab795.png',
  '/assets/figma/be5800e9203a1c9686c0412b57694b0a01ec7994.svg': '/assets/figma/be5800e9203a1c9686c0412b57694b0a01ec7994.svg',
  '/assets/figma/c00ee1b0f3987e8b959d56c2ed5deb022e0f5058.svg': '/assets/figma/c00ee1b0f3987e8b959d56c2ed5deb022e0f5058.svg',
  '/assets/figma/c17c9682e3a8f521d6c87db31a79d22ed5cfb0eb.png': '/assets/figma/c17c9682e3a8f521d6c87db31a79d22ed5cfb0eb.png',
  '/assets/figma/c29d63c27e7df36494d7f3aff59b372f9c9f583a.png': '/assets/figma/c29d63c27e7df36494d7f3aff59b372f9c9f583a.png',
  '/assets/figma/ca3ad8c84baf30eb8f39e657e2a0f6ba5d5fdb9f.svg': '/assets/figma/ca3ad8c84baf30eb8f39e657e2a0f6ba5d5fdb9f.svg',
  '/assets/figma/caec52c1415ad373726ca39d9a5bdc8bbd8e4b40.svg': '/assets/figma/caec52c1415ad373726ca39d9a5bdc8bbd8e4b40.svg',
  '/assets/figma/ce031bae6f109c931e6e8c54c91c1b80d7cddd30.png': '/assets/figma/ce031bae6f109c931e6e8c54c91c1b80d7cddd30.png',
  '/assets/figma/d0dcd90132612641a0109cc9bb9b63ddd311016b.png': '/assets/figma/d0dcd90132612641a0109cc9bb9b63ddd311016b.png',
  '/assets/figma/d5984d67afde25a9c0d3a6d52f239892845003d0.svg': '/assets/figma/d5984d67afde25a9c0d3a6d52f239892845003d0.svg',
  '/assets/figma/d8c1031078e0ccaff5f5cdfa52b50da5f4cffe28.svg': '/assets/figma/d8c1031078e0ccaff5f5cdfa52b50da5f4cffe28.svg',
  '/assets/figma/defd24b0ba2543a683d1c21866cf1b5c65c558aa.png': '/assets/figma/defd24b0ba2543a683d1c21866cf1b5c65c558aa.png',
  '/assets/figma/ede18ac1c950c4f99134c1e1931b338cca024c70.svg': '/assets/figma/ede18ac1c950c4f99134c1e1931b338cca024c70.svg',
  '/assets/figma/f63330de568648bbb48442a34ec4916db91c2b91.svg': '/assets/figma/f63330de568648bbb48442a34ec4916db91c2b91.svg',
  '/assets/figma/fb1a185f54c2dad88591f06c1a5ad030afc46ea8.svg': '/assets/figma/fb1a185f54c2dad88591f06c1a5ad030afc46ea8.svg',
  '/assets/figma/fd2f7ce9ab67910301d015e53f3cd620d0051927.png': '/assets/figma/fd2f7ce9ab67910301d015e53f3cd620d0051927.png',
}

/**
 * Resolve a Figma localhost asset URL to a local public path.
 *
 * - In production (or when Figma Desktop is not running) this returns the
 *   local `/assets/figma/<hash>.<ext>` path from the public folder.
 * - Falls back to the original URL when the asset isn't in the map, which
 *   works fine in development while Figma Desktop is running.
 */
export function figmaAsset(url: string): string {
  return FIGMA_ASSET_MAP[url] ?? url
}

export { FIGMA_ASSET_MAP }
